'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_LCN_AUDIT_IN_DETAIL

    '''<summary>
    '''Txt_Write_At control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Write_At As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Write_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Write_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_location_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_location_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lcnno_dispaly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcnno_dispaly As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_location_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_location_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RDB_CER_PRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDB_CER_PRO As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RDB_SUB_CER_PRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDB_SUB_CER_PRO As Global.System.Web.UI.WebControls.RadioButtonList
End Class
