'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_LCN_SUB

    '''<summary>
    '''rdl_lcn_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_lcn_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txt_sub_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_phr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_phr_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_iden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_iden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_lcnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_lcnno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_amphor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_amphor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_changwat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_opentime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_PURPOSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_PURPOSE As Global.System.Web.UI.WebControls.TextBox
End Class
