'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POPUP_TABEAN_OLD_TO_TABEAN_WHO

    '''<summary>
    '''txt_RGTNO_NEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RGTNO_NEW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NAME_THAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_name_request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_name_request As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_name_request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_name_request As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXT_SEARCH_TN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_SEARCH_TN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_SEARCH_TN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SEARCH_TN As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_type_lcn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_type_lcn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_THANM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_THANM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_LCNNO_DISPAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LCNNO_DISPAY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''E1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents E1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button
End Class
