'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TRANSFER_DETAIL

    '''<summary>
    '''head_tabean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head_tabean As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NAME_TB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_TB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_PLACE_TB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_PLACE_TB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''data_show3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data_show3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_agent99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_agent99 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_person_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_person_age As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_NATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_NATION As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''data_show1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data_show1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''data_show2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data_show2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_nation_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nation_person As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_TYPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_TYPE_NAME As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_TYPE_SUB_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_TYPE_SUB_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_CATEGORY_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_CATEGORY_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lab_category_out_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lab_category_out_id As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DD_CATEGORY_OUT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_CATEGORY_OUT_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_THAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_STYPE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_STYPE_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SIZE_PACK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIZE_PACK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''NATURE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NATURE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''STAFF_KEY_SET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STAFF_KEY_SET As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NO_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_MANUFAC_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_MANUFAC_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''DD_SYNDROME_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_SYNDROME_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PROPERTIES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PROPERTIES As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SIZE_USE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIZE_USE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HOW_USE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HOW_USE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_EATTING_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_EATTING_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''R_EATTING_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_EATTING_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DD_EATING_CONDITION_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_EATING_CONDITION_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''R_EATING_CONDITION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_EATING_CONDITION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''EATING_CONDITION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EATING_CONDITION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_STORAGE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_STORAGE_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TREATMENT_AGE_YEAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TREATMENT_AGE_YEAR As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''div_hide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_hide As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TREATMENT_AGE_MONTH_SUB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TREATMENT_AGE_MONTH_SUB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''div_hide2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_hide2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''R_CONTRAINDICATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CONTRAINDICATION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''R_CONTRAINDICATION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CONTRAINDICATION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CONTRAINDICATION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CONTRAINDICATION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_WARNING_TYPE_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_WARNING_TYPE_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''WARNING_TYPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WARNING_TYPE_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_WARNING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_WARNING As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''DD_WARNING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_WARNING As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_WARNING_SUB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_WARNING_SUB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''R_WARNING_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_WARNING_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''WARNING_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WARNING_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_CAUTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CAUTION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''R_CAUTION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CAUTION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CAUTION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAUTION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_ADV_REACTIVETION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_ADV_REACTIVETION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''R_ADV_REACTIVETION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_ADV_REACTIVETION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ADV_REACTIVETION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ADV_REACTIVETION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SALE_CHANNEL_SET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SALE_CHANNEL_SET As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DD_SALE_CHANNEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_SALE_CHANNEL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RECIPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RECIPE_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_RECIPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_RECIPE_NAME As Global.System.Web.UI.WebControls.DropDownList
End Class
