'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_CONFIRM_REPRESENT

    '''<summary>
    '''lbl_lcn_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lcn_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_BSN_THAIFULLNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_BSN_THAIFULLNAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_BSN_IDENTIFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_BSN_IDENTIFY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thanameplace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thanameplace As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thaaddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thaaddr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thabuilding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thabuilding As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thamu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thamu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thasoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thasoi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_tharoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_tharoad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thathmblnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thathmblnm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thaamphrnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thaamphrnm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_thachngwtnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_thachngwtnm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_zipcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lct_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lct_tel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label17 As Global.System.Web.UI.WebControls.Label
End Class
