'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_LCN_UPLOAD_FILE

    '''<summary>
    '''lbl_person_type1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type3 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type4 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type5 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''rdl_chk_local control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_chk_local As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''UC_ATTACH_LCN_NO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_NO1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_NO1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_NO1_1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_NO1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_NO1_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_NO1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_NO1_3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_NO1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_NO1_4 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_NO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_NO2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rdl_chk_bsn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_chk_bsn As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''UC_ATTACH_LCN_BSN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_BSN1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_BSN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_BSN2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_BSN2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_BSN2_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UC_ATTACH_LCN7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN7 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN8 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_1_1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_1_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_1_3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_1_4 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_1_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_1_5 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_2_1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_2_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_2_3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_2_4 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_2_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_2_5 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_3_1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_3_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_3_3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_3_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_3_4 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_4_1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_4_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_4_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_4_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_4_3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_4_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_4_4 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_4_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_4_5 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_5_1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_5_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_5_2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_5_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_5_3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_5_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_5_4 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''Panel_posormo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_posormo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UC_ATTACH_LCN_PSM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_PSM1 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_PSM2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_PSM2 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''UC_ATTACH_LCN_PSM3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN_PSM3 As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''BTN_UPLOAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_UPLOAD As Global.System.Web.UI.WebControls.Button
End Class
