'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_LCN_UPLOAD_FILE

    '''<summary>
    '''lbl_person_type1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type3 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type4 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lbl_person_type5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_person_type5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_person_type5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_person_type5 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''show_local_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents show_local_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_chk_local control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_chk_local As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''show_bsn_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents show_bsn_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rdl_chk_bsn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_chk_bsn As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btn_select_typeatt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_select_typeatt As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tb_type_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_type_menu As Global.System.Web.UI.WebControls.Table
End Class
