'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POPUP_LCN_PHR_DETAIL

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ddl_worker_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_worker_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_PHR_LEVEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_LEVEL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_prefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_prefix As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_PHR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PHR_TEXT_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_TEXT_NUM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_STUDY_LEVEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_STUDY_LEVEL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PHR_VETERINARY_FIELD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_VETERINARY_FIELD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PHR_TEXT_JOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_TEXT_JOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PHR_TEXT_WORK_TIME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_TEXT_WORK_TIME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_job control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_job As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_law control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_law As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rgns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgns As Global.Telerik.Web.UI.RadGrid
End Class
