'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_INFORM_DEDAIL

    '''<summary>
    '''Txt_Write_At control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Write_At As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Write_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Write_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_INFORM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_INFORM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''T1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_IDEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_IDEN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''T2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''T3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''T4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_name_thai_inform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_name_thai_inform As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''T5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''T6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_name_eng_inform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_name_eng_inform As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''T7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txt_INFORM_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_INFORM_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CB_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LABEL_NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LABEL_NAME_THAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LABEL_NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LABEL_NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NAME_THAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CB_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CB_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_size_pack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_size_pack As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_size_pack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_size_pack As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CB_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CB_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CB_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''label_SIZE_USE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label_SIZE_USE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SIZE_USE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SIZE_USE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CB_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SUB_CB_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUB_CB_7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LABEL_EATTING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LABEL_EATTING As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_EATTING_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_EATTING_ID As Global.System.Web.UI.WebControls.DropDownList
End Class
