'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_INFORM_DEDAIL2

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DIV_NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_NAME_THAI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_THAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_THAI_NEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_THAI_NEW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DIV_NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_NAME_ENG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_ENG_NEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_ENG_NEW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DIV_NAME_OTHER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_NAME_OTHER As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NAME_OTHER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_OTHER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_OTHER_NEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_OTHER_NEW As Global.System.Web.UI.WebControls.TextBox
End Class
