'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_SUBSTITUTE_DETAIL

    '''<summary>
    '''rdl_tbn_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_tbn_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cb_Personal_Type1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Personal_Type1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_thanm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_thanm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_person_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_person_age As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Nation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Nation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_iden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_iden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_Personal_Type2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Personal_Type2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_NitiName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NitiName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_idenNiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_idenNiti As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_alternate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_alternate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_alternate_Old control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_alternate_Old As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Nationnal_Niti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Nationnal_Niti As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_idenAlternate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_idenAlternate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NameThai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NameThai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NameEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NameEng As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NumNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NumNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_sub_purpose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_sub_purpose As Global.System.Web.UI.WebControls.DropDownList
End Class
