'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POPUP_LCN_TRANSFER

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''rdl_lcn_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_lcn_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_name_lcn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_name_lcn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_phr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_phr_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_phr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_niti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_niti As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lcnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lcnno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_lcnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcnno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_name_business control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_name_business As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_name_business control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_name_business As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_location_trnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_location_trnf As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_location_trnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_location_trnf As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_building As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_mu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_soi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_road As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_tambol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_amphor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_amphor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_amphor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_amphor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_changwat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_changwat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_zipcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_lcn_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lcn_tel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_lcn_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcn_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_time_work control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_time_work As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadTimePicker1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTimePicker1 As Global.Telerik.Web.UI.RadTimePicker

    '''<summary>
    '''lbl_trnf_iden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_iden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_iden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_iden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_PASSPORT_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PASSPORT_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PASSPORT_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PASSPORT_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_PASSPORT_EXPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PASSPORT_EXPDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RDP_PASSPORT_EXPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDP_PASSPORT_EXPDATE As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''lbl_DOC_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DOC_NO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_DOC_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DOC_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_DOC_NO_EXPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DOC_NO_EXPDATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RDP_DOC_NO_EXPDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDP_DOC_NO_EXPDATE As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''lbl_transfer_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_transfer_to As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_transfer_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_transfer_to As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_trnf_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_operator_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_operator_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_operator_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_operator_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_start_trnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_start_trnf As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPD_start_trnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPD_start_trnf As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''lbl_trnf_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_trnf_remark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_trnf_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_trnf_remark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Confirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel As Global.System.Web.UI.WebControls.Button
End Class
