'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_LCN_AUDIT_OUT_DETAIL_GROUP_DRUG

    '''<summary>
    '''txt_Name_Production_site control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Name_Production_site As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_type_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_type_menu As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''txt_name_more control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_name_more As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tel_more control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tel_more As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mobile_more control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mobile_more As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_email_more control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_email_more As Global.System.Web.UI.WebControls.TextBox
End Class
