'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_LCN_EDIT

    '''<summary>
    '''rdl_lcn_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_lcn_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txt_sub_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_phr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_phr_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_iden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_iden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_lcnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_lcnno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_amphor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_amphor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_changwat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_sub_opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sub_opentime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''edit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents edit1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DDL_EDIT_REASON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_EDIT_REASON As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lb_select_reason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_select_reason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDL_EDIT_REASON_SUB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_EDIT_REASON_SUB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''p1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cm1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_upload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tb_type_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_type_menu As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''edit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents edit2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_reason_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_reason_name As Global.System.Web.UI.WebControls.TextBox
End Class
