'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_PHR_DETAIL

    '''<summary>
    '''Txt_Write_At control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Write_At As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Write_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Write_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_CTZNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_CTZNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_PHR_CTZNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PHR_CTZNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_phr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_age As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_age As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Nationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Nationality As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_Building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_Building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_Soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_Soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_ampher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_ampher As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_changwat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_phone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_phr_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_phr_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Div_Txt_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_Txt_num As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_PHR_TEXT_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_TEXT_NUM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Div_Qualificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_Qualificate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DDL_STUDY_LEVEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_STUDY_LEVEL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Div_Major control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_Major As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddl_phr_type_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_phr_type_other As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_Study_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Study_Year As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_TEXT_WORK_TIME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_TEXT_WORK_TIME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_training_phr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_training_phr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rdp_SIMINAR_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_SIMINAR_DATE As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdp_SIMINAR_DATE_END control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_SIMINAR_DATE_END As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''btn_save_training control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_training As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rgns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgns As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''txt_addr_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_addr_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_Matra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Matra As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_Name_Bsn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Name_Bsn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_Building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_Building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_Soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_Soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_Province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Province As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_Province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Province As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_BSN_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_amphor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_amphor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_tambol As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_BSN_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_Opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_Opentime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_BSN_Opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_BSN_Opentime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rdl_Phr_Service_Chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_Phr_Service_Chk As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txt_Phr_Service_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Phr_Service_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Service_Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Service_Time As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Service_Time_Open control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Service_Time_Open As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_Service_Time_Open control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Service_Time_Open As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Service_Time_Close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Service_Time_Close As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Business_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Business_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HOME_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HOME_NO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_house_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_house_no As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTN_SEARCH_HOME_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SEARCH_HOME_NO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_BN_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BN_Building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_Building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BN_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BN_Soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_Soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BN_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_bn_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_bn_changwat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_bn_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bn_changwat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_BN_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BN_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_bn_ampher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_bn_ampher As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_bn_ampher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bn_ampher As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_bn_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_bn_tambol As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_bn_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bn_tambol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_BN_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BN_Opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BN_Opentime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_BN_Opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_BN_Opentime As Global.System.Web.UI.WebControls.Label
End Class
