'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POPUP_PREVIEW_UPLOAD

    '''<summary>
    '''UC_UPLOAD_PREVIEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_UPLOAD_PREVIEW As Global.FDA_DRUG_HERB.UC_UPLOAD_PREVIEW
End Class
