'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LGT_DRUG_DEMO")>  _
Partial Public Class LINQ_REPORTDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertHERB_PRODUCT_REPORT_DETAIL(instance As HERB_PRODUCT_REPORT_DETAIL)
    End Sub
  Partial Private Sub UpdateHERB_PRODUCT_REPORT_DETAIL(instance As HERB_PRODUCT_REPORT_DETAIL)
    End Sub
  Partial Private Sub DeleteHERB_PRODUCT_REPORT_DETAIL(instance As HERB_PRODUCT_REPORT_DETAIL)
    End Sub
  Partial Private Sub InsertHERB_PRODUCT_REPORT(instance As HERB_PRODUCT_REPORT)
    End Sub
  Partial Private Sub UpdateHERB_PRODUCT_REPORT(instance As HERB_PRODUCT_REPORT)
    End Sub
  Partial Private Sub DeleteHERB_PRODUCT_REPORT(instance As HERB_PRODUCT_REPORT)
    End Sub
  Partial Private Sub InsertHERB_PRODUCT_NOTIFIED(instance As HERB_PRODUCT_NOTIFIED)
    End Sub
  Partial Private Sub UpdateHERB_PRODUCT_NOTIFIED(instance As HERB_PRODUCT_NOTIFIED)
    End Sub
  Partial Private Sub DeleteHERB_PRODUCT_NOTIFIED(instance As HERB_PRODUCT_NOTIFIED)
    End Sub
  Partial Private Sub InsertHERB_PRODUCT_NOTIFIED_DETAIL(instance As HERB_PRODUCT_NOTIFIED_DETAIL)
    End Sub
  Partial Private Sub UpdateHERB_PRODUCT_NOTIFIED_DETAIL(instance As HERB_PRODUCT_NOTIFIED_DETAIL)
    End Sub
  Partial Private Sub DeleteHERB_PRODUCT_NOTIFIED_DETAIL(instance As HERB_PRODUCT_NOTIFIED_DETAIL)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("LGT_DRUGConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property HERB_PRODUCT_REPORT_DETAILs() As System.Data.Linq.Table(Of HERB_PRODUCT_REPORT_DETAIL)
		Get
			Return Me.GetTable(Of HERB_PRODUCT_REPORT_DETAIL)
		End Get
	End Property
	
	Public ReadOnly Property HERB_PRODUCT_REPORTs() As System.Data.Linq.Table(Of HERB_PRODUCT_REPORT)
		Get
			Return Me.GetTable(Of HERB_PRODUCT_REPORT)
		End Get
	End Property
	
	Public ReadOnly Property HERB_PRODUCT_NOTIFIEDs() As System.Data.Linq.Table(Of HERB_PRODUCT_NOTIFIED)
		Get
			Return Me.GetTable(Of HERB_PRODUCT_NOTIFIED)
		End Get
	End Property
	
	Public ReadOnly Property HERB_PRODUCT_NOTIFIED_DETAILs() As System.Data.Linq.Table(Of HERB_PRODUCT_NOTIFIED_DETAIL)
		Get
			Return Me.GetTable(Of HERB_PRODUCT_NOTIFIED_DETAIL)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.HERB_PRODUCT_REPORT_DETAIL")>  _
Partial Public Class HERB_PRODUCT_REPORT_DETAIL
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _Name As String
	
	Private _Scientific_Name As String
	
	Private _Packing_Size_Details As String
	
	Private _Quantity As String
	
	Private _Total_Quantity As String
	
	Private _Sale_Unit As String
	
	Private _Note As String
	
	Private _Country As String
	
	Private _Manufacturer_Name As String
	
	Private _Voucher_Number As String
	
	Private _SEQ As System.Nullable(Of Integer)
	
	Private _IS_USE As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnScientific_NameChanging(value As String)
    End Sub
    Partial Private Sub OnScientific_NameChanged()
    End Sub
    Partial Private Sub OnPacking_Size_DetailsChanging(value As String)
    End Sub
    Partial Private Sub OnPacking_Size_DetailsChanged()
    End Sub
    Partial Private Sub OnQuantityChanging(value As String)
    End Sub
    Partial Private Sub OnQuantityChanged()
    End Sub
    Partial Private Sub OnTotal_QuantityChanging(value As String)
    End Sub
    Partial Private Sub OnTotal_QuantityChanged()
    End Sub
    Partial Private Sub OnSale_UnitChanging(value As String)
    End Sub
    Partial Private Sub OnSale_UnitChanged()
    End Sub
    Partial Private Sub OnNoteChanging(value As String)
    End Sub
    Partial Private Sub OnNoteChanged()
    End Sub
    Partial Private Sub OnCountryChanging(value As String)
    End Sub
    Partial Private Sub OnCountryChanged()
    End Sub
    Partial Private Sub OnManufacturer_NameChanging(value As String)
    End Sub
    Partial Private Sub OnManufacturer_NameChanged()
    End Sub
    Partial Private Sub OnVoucher_NumberChanging(value As String)
    End Sub
    Partial Private Sub OnVoucher_NumberChanged()
    End Sub
    Partial Private Sub OnSEQChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSEQChanged()
    End Sub
    Partial Private Sub OnIS_USEChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIS_USEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Scientific_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Scientific_Name() As String
		Get
			Return Me._Scientific_Name
		End Get
		Set
			If (String.Equals(Me._Scientific_Name, value) = false) Then
				Me.OnScientific_NameChanging(value)
				Me.SendPropertyChanging
				Me._Scientific_Name = value
				Me.SendPropertyChanged("Scientific_Name")
				Me.OnScientific_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Packing_Size_Details", DbType:="NVarChar(MAX)")>  _
	Public Property Packing_Size_Details() As String
		Get
			Return Me._Packing_Size_Details
		End Get
		Set
			If (String.Equals(Me._Packing_Size_Details, value) = false) Then
				Me.OnPacking_Size_DetailsChanging(value)
				Me.SendPropertyChanging
				Me._Packing_Size_Details = value
				Me.SendPropertyChanged("Packing_Size_Details")
				Me.OnPacking_Size_DetailsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Quantity", DbType:="NVarChar(MAX)")>  _
	Public Property Quantity() As String
		Get
			Return Me._Quantity
		End Get
		Set
			If (String.Equals(Me._Quantity, value) = false) Then
				Me.OnQuantityChanging(value)
				Me.SendPropertyChanging
				Me._Quantity = value
				Me.SendPropertyChanged("Quantity")
				Me.OnQuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total_Quantity", DbType:="NVarChar(MAX)")>  _
	Public Property Total_Quantity() As String
		Get
			Return Me._Total_Quantity
		End Get
		Set
			If (String.Equals(Me._Total_Quantity, value) = false) Then
				Me.OnTotal_QuantityChanging(value)
				Me.SendPropertyChanging
				Me._Total_Quantity = value
				Me.SendPropertyChanged("Total_Quantity")
				Me.OnTotal_QuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Sale_Unit", DbType:="NVarChar(MAX)")>  _
	Public Property Sale_Unit() As String
		Get
			Return Me._Sale_Unit
		End Get
		Set
			If (String.Equals(Me._Sale_Unit, value) = false) Then
				Me.OnSale_UnitChanging(value)
				Me.SendPropertyChanging
				Me._Sale_Unit = value
				Me.SendPropertyChanged("Sale_Unit")
				Me.OnSale_UnitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Note", DbType:="NVarChar(MAX)")>  _
	Public Property Note() As String
		Get
			Return Me._Note
		End Get
		Set
			If (String.Equals(Me._Note, value) = false) Then
				Me.OnNoteChanging(value)
				Me.SendPropertyChanging
				Me._Note = value
				Me.SendPropertyChanged("Note")
				Me.OnNoteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Country", DbType:="NVarChar(MAX)")>  _
	Public Property Country() As String
		Get
			Return Me._Country
		End Get
		Set
			If (String.Equals(Me._Country, value) = false) Then
				Me.OnCountryChanging(value)
				Me.SendPropertyChanging
				Me._Country = value
				Me.SendPropertyChanged("Country")
				Me.OnCountryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Manufacturer_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Manufacturer_Name() As String
		Get
			Return Me._Manufacturer_Name
		End Get
		Set
			If (String.Equals(Me._Manufacturer_Name, value) = false) Then
				Me.OnManufacturer_NameChanging(value)
				Me.SendPropertyChanging
				Me._Manufacturer_Name = value
				Me.SendPropertyChanged("Manufacturer_Name")
				Me.OnManufacturer_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Voucher_Number", DbType:="NVarChar(MAX)")>  _
	Public Property Voucher_Number() As String
		Get
			Return Me._Voucher_Number
		End Get
		Set
			If (String.Equals(Me._Voucher_Number, value) = false) Then
				Me.OnVoucher_NumberChanging(value)
				Me.SendPropertyChanging
				Me._Voucher_Number = value
				Me.SendPropertyChanged("Voucher_Number")
				Me.OnVoucher_NumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEQ", DbType:="Int")>  _
	Public Property SEQ() As System.Nullable(Of Integer)
		Get
			Return Me._SEQ
		End Get
		Set
			If (Me._SEQ.Equals(value) = false) Then
				Me.OnSEQChanging(value)
				Me.SendPropertyChanging
				Me._SEQ = value
				Me.SendPropertyChanged("SEQ")
				Me.OnSEQChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IS_USE", DbType:="Bit")>  _
	Public Property IS_USE() As System.Nullable(Of Boolean)
		Get
			Return Me._IS_USE
		End Get
		Set
			If (Me._IS_USE.Equals(value) = false) Then
				Me.OnIS_USEChanging(value)
				Me.SendPropertyChanging
				Me._IS_USE = value
				Me.SendPropertyChanged("IS_USE")
				Me.OnIS_USEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.HERB_PRODUCT_REPORT")>  _
Partial Public Class HERB_PRODUCT_REPORT
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _STATUS_ID As System.Nullable(Of Integer)
	
	Private _PROCESS_ID As System.Nullable(Of Integer)
	
	Private _TR_ID As System.Nullable(Of Integer)
	
	Private _FK_LCT As System.Nullable(Of Integer)
	
	Private _FK_LCN As System.Nullable(Of Integer)
	
	Private _LCNNO As String
	
	Private _LCNNO_NEW As String
	
	Private _lcntpcd As String
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _CITIZEN_ID As String
	
	Private _CITIZEN_ID_AUTHORIZE As String
	
	Private _rcvno As String
	
	Private _rcvdate As System.Nullable(Of Date)
	
	Private _rcv_staff_name As String
	
	Private _cnsddate As System.Nullable(Of Date)
	
	Private _frtappdate As System.Nullable(Of Date)
	
	Private _appdate As System.Nullable(Of Date)
	
	Private _app_staff_name As String
	
	Private _WRITE_AT As String
	
	Private _WRITE_DATE As System.Nullable(Of Date)
	
	Private _CREATE_BY As String
	
	Private _CREATE_DATE As System.Nullable(Of Date)
	
	Private _DATE_CONFIRM As System.Nullable(Of Date)
	
	Private _YEAR As String
	
	Private _Loacation_Name As String
	
	Private _Loacation_ADDR As String
	
	Private _tel As String
	
	Private _Fax As String
	
	Private _ACTIVEFACT As System.Nullable(Of Integer)
	
	Private _STATUS_FILE_UPLOAD As System.Nullable(Of Integer)
	
	Private _RCVNO_NEW As String
	
	Private _csn_staff_name As String
	
	Private _THANM As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnPROCESS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPROCESS_IDChanged()
    End Sub
    Partial Private Sub OnTR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTR_IDChanged()
    End Sub
    Partial Private Sub OnFK_LCTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_LCTChanged()
    End Sub
    Partial Private Sub OnFK_LCNChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_LCNChanged()
    End Sub
    Partial Private Sub OnLCNNOChanging(value As String)
    End Sub
    Partial Private Sub OnLCNNOChanged()
    End Sub
    Partial Private Sub OnLCNNO_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnLCNNO_NEWChanged()
    End Sub
    Partial Private Sub OnlcntpcdChanging(value As String)
    End Sub
    Partial Private Sub OnlcntpcdChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnrcvnoChanging(value As String)
    End Sub
    Partial Private Sub OnrcvnoChanged()
    End Sub
    Partial Private Sub OnrcvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnrcvdateChanged()
    End Sub
    Partial Private Sub Onrcv_staff_nameChanging(value As String)
    End Sub
    Partial Private Sub Onrcv_staff_nameChanged()
    End Sub
    Partial Private Sub OncnsddateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OncnsddateChanged()
    End Sub
    Partial Private Sub OnfrtappdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnfrtappdateChanged()
    End Sub
    Partial Private Sub OnappdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnappdateChanged()
    End Sub
    Partial Private Sub Onapp_staff_nameChanging(value As String)
    End Sub
    Partial Private Sub Onapp_staff_nameChanged()
    End Sub
    Partial Private Sub OnWRITE_ATChanging(value As String)
    End Sub
    Partial Private Sub OnWRITE_ATChanged()
    End Sub
    Partial Private Sub OnWRITE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnWRITE_DATEChanged()
    End Sub
    Partial Private Sub OnCREATE_BYChanging(value As String)
    End Sub
    Partial Private Sub OnCREATE_BYChanged()
    End Sub
    Partial Private Sub OnCREATE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCREATE_DATEChanged()
    End Sub
    Partial Private Sub OnDATE_CONFIRMChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDATE_CONFIRMChanged()
    End Sub
    Partial Private Sub OnYEARChanging(value As String)
    End Sub
    Partial Private Sub OnYEARChanged()
    End Sub
    Partial Private Sub OnLoacation_NameChanging(value As String)
    End Sub
    Partial Private Sub OnLoacation_NameChanged()
    End Sub
    Partial Private Sub OnLoacation_ADDRChanging(value As String)
    End Sub
    Partial Private Sub OnLoacation_ADDRChanged()
    End Sub
    Partial Private Sub OntelChanging(value As String)
    End Sub
    Partial Private Sub OntelChanged()
    End Sub
    Partial Private Sub OnFaxChanging(value As String)
    End Sub
    Partial Private Sub OnFaxChanged()
    End Sub
    Partial Private Sub OnACTIVEFACTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVEFACTChanged()
    End Sub
    Partial Private Sub OnSTATUS_FILE_UPLOADChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_FILE_UPLOADChanged()
    End Sub
    Partial Private Sub OnRCVNO_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnRCVNO_NEWChanged()
    End Sub
    Partial Private Sub Oncsn_staff_nameChanging(value As String)
    End Sub
    Partial Private Sub Oncsn_staff_nameChanged()
    End Sub
    Partial Private Sub OnTHANMChanging(value As String)
    End Sub
    Partial Private Sub OnTHANMChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="Int")>  _
	Public Property STATUS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (Me._STATUS_ID.Equals(value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROCESS_ID", DbType:="Int")>  _
	Public Property PROCESS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._PROCESS_ID
		End Get
		Set
			If (Me._PROCESS_ID.Equals(value) = false) Then
				Me.OnPROCESS_IDChanging(value)
				Me.SendPropertyChanging
				Me._PROCESS_ID = value
				Me.SendPropertyChanged("PROCESS_ID")
				Me.OnPROCESS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TR_ID", DbType:="Int")>  _
	Public Property TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._TR_ID
		End Get
		Set
			If (Me._TR_ID.Equals(value) = false) Then
				Me.OnTR_IDChanging(value)
				Me.SendPropertyChanging
				Me._TR_ID = value
				Me.SendPropertyChanged("TR_ID")
				Me.OnTR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_LCT", DbType:="Int")>  _
	Public Property FK_LCT() As System.Nullable(Of Integer)
		Get
			Return Me._FK_LCT
		End Get
		Set
			If (Me._FK_LCT.Equals(value) = false) Then
				Me.OnFK_LCTChanging(value)
				Me.SendPropertyChanging
				Me._FK_LCT = value
				Me.SendPropertyChanged("FK_LCT")
				Me.OnFK_LCTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_LCN", DbType:="Int")>  _
	Public Property FK_LCN() As System.Nullable(Of Integer)
		Get
			Return Me._FK_LCN
		End Get
		Set
			If (Me._FK_LCN.Equals(value) = false) Then
				Me.OnFK_LCNChanging(value)
				Me.SendPropertyChanging
				Me._FK_LCN = value
				Me.SendPropertyChanged("FK_LCN")
				Me.OnFK_LCNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNNO", DbType:="NVarChar(MAX)")>  _
	Public Property LCNNO() As String
		Get
			Return Me._LCNNO
		End Get
		Set
			If (String.Equals(Me._LCNNO, value) = false) Then
				Me.OnLCNNOChanging(value)
				Me.SendPropertyChanging
				Me._LCNNO = value
				Me.SendPropertyChanged("LCNNO")
				Me.OnLCNNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNNO_NEW", DbType:="NVarChar(MAX)")>  _
	Public Property LCNNO_NEW() As String
		Get
			Return Me._LCNNO_NEW
		End Get
		Set
			If (String.Equals(Me._LCNNO_NEW, value) = false) Then
				Me.OnLCNNO_NEWChanging(value)
				Me.SendPropertyChanging
				Me._LCNNO_NEW = value
				Me.SendPropertyChanged("LCNNO_NEW")
				Me.OnLCNNO_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntpcd", DbType:="NVarChar(MAX)")>  _
	Public Property lcntpcd() As String
		Get
			Return Me._lcntpcd
		End Get
		Set
			If (String.Equals(Me._lcntpcd, value) = false) Then
				Me.OnlcntpcdChanging(value)
				Me.SendPropertyChanging
				Me._lcntpcd = value
				Me.SendPropertyChanged("lcntpcd")
				Me.OnlcntpcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID_AUTHORIZE() As String
		Get
			Return Me._CITIZEN_ID_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_AUTHORIZE, value) = false) Then
				Me.OnCITIZEN_ID_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_AUTHORIZE = value
				Me.SendPropertyChanged("CITIZEN_ID_AUTHORIZE")
				Me.OnCITIZEN_ID_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvno", DbType:="NVarChar(MAX)")>  _
	Public Property rcvno() As String
		Get
			Return Me._rcvno
		End Get
		Set
			If (String.Equals(Me._rcvno, value) = false) Then
				Me.OnrcvnoChanging(value)
				Me.SendPropertyChanging
				Me._rcvno = value
				Me.SendPropertyChanged("rcvno")
				Me.OnrcvnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate", DbType:="Date")>  _
	Public Property rcvdate() As System.Nullable(Of Date)
		Get
			Return Me._rcvdate
		End Get
		Set
			If (Me._rcvdate.Equals(value) = false) Then
				Me.OnrcvdateChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate = value
				Me.SendPropertyChanged("rcvdate")
				Me.OnrcvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcv_staff_name", DbType:="NVarChar(MAX)")>  _
	Public Property rcv_staff_name() As String
		Get
			Return Me._rcv_staff_name
		End Get
		Set
			If (String.Equals(Me._rcv_staff_name, value) = false) Then
				Me.Onrcv_staff_nameChanging(value)
				Me.SendPropertyChanging
				Me._rcv_staff_name = value
				Me.SendPropertyChanged("rcv_staff_name")
				Me.Onrcv_staff_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnsddate", DbType:="Date")>  _
	Public Property cnsddate() As System.Nullable(Of Date)
		Get
			Return Me._cnsddate
		End Get
		Set
			If (Me._cnsddate.Equals(value) = false) Then
				Me.OncnsddateChanging(value)
				Me.SendPropertyChanging
				Me._cnsddate = value
				Me.SendPropertyChanged("cnsddate")
				Me.OncnsddateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frtappdate", DbType:="Date")>  _
	Public Property frtappdate() As System.Nullable(Of Date)
		Get
			Return Me._frtappdate
		End Get
		Set
			If (Me._frtappdate.Equals(value) = false) Then
				Me.OnfrtappdateChanging(value)
				Me.SendPropertyChanging
				Me._frtappdate = value
				Me.SendPropertyChanged("frtappdate")
				Me.OnfrtappdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appdate", DbType:="Date")>  _
	Public Property appdate() As System.Nullable(Of Date)
		Get
			Return Me._appdate
		End Get
		Set
			If (Me._appdate.Equals(value) = false) Then
				Me.OnappdateChanging(value)
				Me.SendPropertyChanging
				Me._appdate = value
				Me.SendPropertyChanged("appdate")
				Me.OnappdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_app_staff_name", DbType:="NVarChar(MAX)")>  _
	Public Property app_staff_name() As String
		Get
			Return Me._app_staff_name
		End Get
		Set
			If (String.Equals(Me._app_staff_name, value) = false) Then
				Me.Onapp_staff_nameChanging(value)
				Me.SendPropertyChanging
				Me._app_staff_name = value
				Me.SendPropertyChanged("app_staff_name")
				Me.Onapp_staff_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WRITE_AT", DbType:="NVarChar(MAX)")>  _
	Public Property WRITE_AT() As String
		Get
			Return Me._WRITE_AT
		End Get
		Set
			If (String.Equals(Me._WRITE_AT, value) = false) Then
				Me.OnWRITE_ATChanging(value)
				Me.SendPropertyChanging
				Me._WRITE_AT = value
				Me.SendPropertyChanged("WRITE_AT")
				Me.OnWRITE_ATChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WRITE_DATE", DbType:="Date")>  _
	Public Property WRITE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._WRITE_DATE
		End Get
		Set
			If (Me._WRITE_DATE.Equals(value) = false) Then
				Me.OnWRITE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._WRITE_DATE = value
				Me.SendPropertyChanged("WRITE_DATE")
				Me.OnWRITE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_BY", DbType:="NVarChar(MAX)")>  _
	Public Property CREATE_BY() As String
		Get
			Return Me._CREATE_BY
		End Get
		Set
			If (String.Equals(Me._CREATE_BY, value) = false) Then
				Me.OnCREATE_BYChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_BY = value
				Me.SendPropertyChanged("CREATE_BY")
				Me.OnCREATE_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_DATE", DbType:="Date")>  _
	Public Property CREATE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CREATE_DATE
		End Get
		Set
			If (Me._CREATE_DATE.Equals(value) = false) Then
				Me.OnCREATE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_DATE = value
				Me.SendPropertyChanged("CREATE_DATE")
				Me.OnCREATE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATE_CONFIRM", DbType:="Date")>  _
	Public Property DATE_CONFIRM() As System.Nullable(Of Date)
		Get
			Return Me._DATE_CONFIRM
		End Get
		Set
			If (Me._DATE_CONFIRM.Equals(value) = false) Then
				Me.OnDATE_CONFIRMChanging(value)
				Me.SendPropertyChanging
				Me._DATE_CONFIRM = value
				Me.SendPropertyChanged("DATE_CONFIRM")
				Me.OnDATE_CONFIRMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_YEAR", DbType:="NChar(4)")>  _
	Public Property YEAR() As String
		Get
			Return Me._YEAR
		End Get
		Set
			If (String.Equals(Me._YEAR, value) = false) Then
				Me.OnYEARChanging(value)
				Me.SendPropertyChanging
				Me._YEAR = value
				Me.SendPropertyChanged("YEAR")
				Me.OnYEARChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Loacation_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Loacation_Name() As String
		Get
			Return Me._Loacation_Name
		End Get
		Set
			If (String.Equals(Me._Loacation_Name, value) = false) Then
				Me.OnLoacation_NameChanging(value)
				Me.SendPropertyChanging
				Me._Loacation_Name = value
				Me.SendPropertyChanged("Loacation_Name")
				Me.OnLoacation_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Loacation_ADDR", DbType:="NVarChar(MAX)")>  _
	Public Property Loacation_ADDR() As String
		Get
			Return Me._Loacation_ADDR
		End Get
		Set
			If (String.Equals(Me._Loacation_ADDR, value) = false) Then
				Me.OnLoacation_ADDRChanging(value)
				Me.SendPropertyChanging
				Me._Loacation_ADDR = value
				Me.SendPropertyChanged("Loacation_ADDR")
				Me.OnLoacation_ADDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tel", DbType:="NVarChar(MAX)")>  _
	Public Property tel() As String
		Get
			Return Me._tel
		End Get
		Set
			If (String.Equals(Me._tel, value) = false) Then
				Me.OntelChanging(value)
				Me.SendPropertyChanging
				Me._tel = value
				Me.SendPropertyChanged("tel")
				Me.OntelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fax", DbType:="NVarChar(MAX)")>  _
	Public Property Fax() As String
		Get
			Return Me._Fax
		End Get
		Set
			If (String.Equals(Me._Fax, value) = false) Then
				Me.OnFaxChanging(value)
				Me.SendPropertyChanging
				Me._Fax = value
				Me.SendPropertyChanged("Fax")
				Me.OnFaxChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVEFACT", DbType:="Int")>  _
	Public Property ACTIVEFACT() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVEFACT
		End Get
		Set
			If (Me._ACTIVEFACT.Equals(value) = false) Then
				Me.OnACTIVEFACTChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVEFACT = value
				Me.SendPropertyChanged("ACTIVEFACT")
				Me.OnACTIVEFACTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_FILE_UPLOAD", DbType:="Int")>  _
	Public Property STATUS_FILE_UPLOAD() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_FILE_UPLOAD
		End Get
		Set
			If (Me._STATUS_FILE_UPLOAD.Equals(value) = false) Then
				Me.OnSTATUS_FILE_UPLOADChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_FILE_UPLOAD = value
				Me.SendPropertyChanged("STATUS_FILE_UPLOAD")
				Me.OnSTATUS_FILE_UPLOADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVNO_NEW", DbType:="NVarChar(MAX)")>  _
	Public Property RCVNO_NEW() As String
		Get
			Return Me._RCVNO_NEW
		End Get
		Set
			If (String.Equals(Me._RCVNO_NEW, value) = false) Then
				Me.OnRCVNO_NEWChanging(value)
				Me.SendPropertyChanging
				Me._RCVNO_NEW = value
				Me.SendPropertyChanged("RCVNO_NEW")
				Me.OnRCVNO_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_csn_staff_name", DbType:="NVarChar(MAX)")>  _
	Public Property csn_staff_name() As String
		Get
			Return Me._csn_staff_name
		End Get
		Set
			If (String.Equals(Me._csn_staff_name, value) = false) Then
				Me.Oncsn_staff_nameChanging(value)
				Me.SendPropertyChanging
				Me._csn_staff_name = value
				Me.SendPropertyChanged("csn_staff_name")
				Me.Oncsn_staff_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_THANM", DbType:="NVarChar(MAX)")>  _
	Public Property THANM() As String
		Get
			Return Me._THANM
		End Get
		Set
			If (String.Equals(Me._THANM, value) = false) Then
				Me.OnTHANMChanging(value)
				Me.SendPropertyChanging
				Me._THANM = value
				Me.SendPropertyChanged("THANM")
				Me.OnTHANMChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.HERB_PRODUCT_NOTIFIED")>  _
Partial Public Class HERB_PRODUCT_NOTIFIED
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _STATUS_ID As System.Nullable(Of Integer)
	
	Private _PROCESS_ID As System.Nullable(Of Integer)
	
	Private _TR_ID As System.Nullable(Of Integer)
	
	Private _FK_LCT As System.Nullable(Of Integer)
	
	Private _FK_LCN As System.Nullable(Of Integer)
	
	Private _LCNNO As String
	
	Private _LCNNO_NEW As String
	
	Private _lcntpcd As String
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _CITIZEN_ID As String
	
	Private _CITIZEN_ID_AUTHORIZE As String
	
	Private _rcvno As String
	
	Private _rcvdate As System.Nullable(Of Date)
	
	Private _rcv_staff_name As String
	
	Private _cnsddate As System.Nullable(Of Date)
	
	Private _frtappdate As System.Nullable(Of Date)
	
	Private _appdate As System.Nullable(Of Date)
	
	Private _app_staff_name As String
	
	Private _WRITE_AT As String
	
	Private _WRITE_DATE As System.Nullable(Of Date)
	
	Private _CREATE_BY As String
	
	Private _CREATE_DATE As System.Nullable(Of Date)
	
	Private _DATE_CONFIRM As System.Nullable(Of Date)
	
	Private _YEAR As String
	
	Private _Loacation_Name As String
	
	Private _Loacation_ADDR As String
	
	Private _tel As String
	
	Private _Fax As String
	
	Private _ACTIVEFACT As System.Nullable(Of Integer)
	
	Private _STATUS_FILE_UPLOAD As System.Nullable(Of Integer)
	
	Private _RCVNO_NEW As String
	
	Private _csn_staff_name As String
	
	Private _THANM As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnPROCESS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPROCESS_IDChanged()
    End Sub
    Partial Private Sub OnTR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTR_IDChanged()
    End Sub
    Partial Private Sub OnFK_LCTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_LCTChanged()
    End Sub
    Partial Private Sub OnFK_LCNChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_LCNChanged()
    End Sub
    Partial Private Sub OnLCNNOChanging(value As String)
    End Sub
    Partial Private Sub OnLCNNOChanged()
    End Sub
    Partial Private Sub OnLCNNO_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnLCNNO_NEWChanged()
    End Sub
    Partial Private Sub OnlcntpcdChanging(value As String)
    End Sub
    Partial Private Sub OnlcntpcdChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnrcvnoChanging(value As String)
    End Sub
    Partial Private Sub OnrcvnoChanged()
    End Sub
    Partial Private Sub OnrcvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnrcvdateChanged()
    End Sub
    Partial Private Sub Onrcv_staff_nameChanging(value As String)
    End Sub
    Partial Private Sub Onrcv_staff_nameChanged()
    End Sub
    Partial Private Sub OncnsddateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OncnsddateChanged()
    End Sub
    Partial Private Sub OnfrtappdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnfrtappdateChanged()
    End Sub
    Partial Private Sub OnappdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnappdateChanged()
    End Sub
    Partial Private Sub Onapp_staff_nameChanging(value As String)
    End Sub
    Partial Private Sub Onapp_staff_nameChanged()
    End Sub
    Partial Private Sub OnWRITE_ATChanging(value As String)
    End Sub
    Partial Private Sub OnWRITE_ATChanged()
    End Sub
    Partial Private Sub OnWRITE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnWRITE_DATEChanged()
    End Sub
    Partial Private Sub OnCREATE_BYChanging(value As String)
    End Sub
    Partial Private Sub OnCREATE_BYChanged()
    End Sub
    Partial Private Sub OnCREATE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCREATE_DATEChanged()
    End Sub
    Partial Private Sub OnDATE_CONFIRMChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDATE_CONFIRMChanged()
    End Sub
    Partial Private Sub OnYEARChanging(value As String)
    End Sub
    Partial Private Sub OnYEARChanged()
    End Sub
    Partial Private Sub OnLoacation_NameChanging(value As String)
    End Sub
    Partial Private Sub OnLoacation_NameChanged()
    End Sub
    Partial Private Sub OnLoacation_ADDRChanging(value As String)
    End Sub
    Partial Private Sub OnLoacation_ADDRChanged()
    End Sub
    Partial Private Sub OntelChanging(value As String)
    End Sub
    Partial Private Sub OntelChanged()
    End Sub
    Partial Private Sub OnFaxChanging(value As String)
    End Sub
    Partial Private Sub OnFaxChanged()
    End Sub
    Partial Private Sub OnACTIVEFACTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVEFACTChanged()
    End Sub
    Partial Private Sub OnSTATUS_FILE_UPLOADChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_FILE_UPLOADChanged()
    End Sub
    Partial Private Sub OnRCVNO_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnRCVNO_NEWChanged()
    End Sub
    Partial Private Sub Oncsn_staff_nameChanging(value As String)
    End Sub
    Partial Private Sub Oncsn_staff_nameChanged()
    End Sub
    Partial Private Sub OnTHANMChanging(value As String)
    End Sub
    Partial Private Sub OnTHANMChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="Int")>  _
	Public Property STATUS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (Me._STATUS_ID.Equals(value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROCESS_ID", DbType:="Int")>  _
	Public Property PROCESS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._PROCESS_ID
		End Get
		Set
			If (Me._PROCESS_ID.Equals(value) = false) Then
				Me.OnPROCESS_IDChanging(value)
				Me.SendPropertyChanging
				Me._PROCESS_ID = value
				Me.SendPropertyChanged("PROCESS_ID")
				Me.OnPROCESS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TR_ID", DbType:="Int")>  _
	Public Property TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._TR_ID
		End Get
		Set
			If (Me._TR_ID.Equals(value) = false) Then
				Me.OnTR_IDChanging(value)
				Me.SendPropertyChanging
				Me._TR_ID = value
				Me.SendPropertyChanged("TR_ID")
				Me.OnTR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_LCT", DbType:="Int")>  _
	Public Property FK_LCT() As System.Nullable(Of Integer)
		Get
			Return Me._FK_LCT
		End Get
		Set
			If (Me._FK_LCT.Equals(value) = false) Then
				Me.OnFK_LCTChanging(value)
				Me.SendPropertyChanging
				Me._FK_LCT = value
				Me.SendPropertyChanged("FK_LCT")
				Me.OnFK_LCTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_LCN", DbType:="Int")>  _
	Public Property FK_LCN() As System.Nullable(Of Integer)
		Get
			Return Me._FK_LCN
		End Get
		Set
			If (Me._FK_LCN.Equals(value) = false) Then
				Me.OnFK_LCNChanging(value)
				Me.SendPropertyChanging
				Me._FK_LCN = value
				Me.SendPropertyChanged("FK_LCN")
				Me.OnFK_LCNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNNO", DbType:="NVarChar(MAX)")>  _
	Public Property LCNNO() As String
		Get
			Return Me._LCNNO
		End Get
		Set
			If (String.Equals(Me._LCNNO, value) = false) Then
				Me.OnLCNNOChanging(value)
				Me.SendPropertyChanging
				Me._LCNNO = value
				Me.SendPropertyChanged("LCNNO")
				Me.OnLCNNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNNO_NEW", DbType:="NVarChar(MAX)")>  _
	Public Property LCNNO_NEW() As String
		Get
			Return Me._LCNNO_NEW
		End Get
		Set
			If (String.Equals(Me._LCNNO_NEW, value) = false) Then
				Me.OnLCNNO_NEWChanging(value)
				Me.SendPropertyChanging
				Me._LCNNO_NEW = value
				Me.SendPropertyChanged("LCNNO_NEW")
				Me.OnLCNNO_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntpcd", DbType:="NVarChar(MAX)")>  _
	Public Property lcntpcd() As String
		Get
			Return Me._lcntpcd
		End Get
		Set
			If (String.Equals(Me._lcntpcd, value) = false) Then
				Me.OnlcntpcdChanging(value)
				Me.SendPropertyChanging
				Me._lcntpcd = value
				Me.SendPropertyChanged("lcntpcd")
				Me.OnlcntpcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID_AUTHORIZE() As String
		Get
			Return Me._CITIZEN_ID_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_AUTHORIZE, value) = false) Then
				Me.OnCITIZEN_ID_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_AUTHORIZE = value
				Me.SendPropertyChanged("CITIZEN_ID_AUTHORIZE")
				Me.OnCITIZEN_ID_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvno", DbType:="NVarChar(MAX)")>  _
	Public Property rcvno() As String
		Get
			Return Me._rcvno
		End Get
		Set
			If (String.Equals(Me._rcvno, value) = false) Then
				Me.OnrcvnoChanging(value)
				Me.SendPropertyChanging
				Me._rcvno = value
				Me.SendPropertyChanged("rcvno")
				Me.OnrcvnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate", DbType:="Date")>  _
	Public Property rcvdate() As System.Nullable(Of Date)
		Get
			Return Me._rcvdate
		End Get
		Set
			If (Me._rcvdate.Equals(value) = false) Then
				Me.OnrcvdateChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate = value
				Me.SendPropertyChanged("rcvdate")
				Me.OnrcvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcv_staff_name", DbType:="NVarChar(MAX)")>  _
	Public Property rcv_staff_name() As String
		Get
			Return Me._rcv_staff_name
		End Get
		Set
			If (String.Equals(Me._rcv_staff_name, value) = false) Then
				Me.Onrcv_staff_nameChanging(value)
				Me.SendPropertyChanging
				Me._rcv_staff_name = value
				Me.SendPropertyChanged("rcv_staff_name")
				Me.Onrcv_staff_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnsddate", DbType:="Date")>  _
	Public Property cnsddate() As System.Nullable(Of Date)
		Get
			Return Me._cnsddate
		End Get
		Set
			If (Me._cnsddate.Equals(value) = false) Then
				Me.OncnsddateChanging(value)
				Me.SendPropertyChanging
				Me._cnsddate = value
				Me.SendPropertyChanged("cnsddate")
				Me.OncnsddateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frtappdate", DbType:="Date")>  _
	Public Property frtappdate() As System.Nullable(Of Date)
		Get
			Return Me._frtappdate
		End Get
		Set
			If (Me._frtappdate.Equals(value) = false) Then
				Me.OnfrtappdateChanging(value)
				Me.SendPropertyChanging
				Me._frtappdate = value
				Me.SendPropertyChanged("frtappdate")
				Me.OnfrtappdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appdate", DbType:="Date")>  _
	Public Property appdate() As System.Nullable(Of Date)
		Get
			Return Me._appdate
		End Get
		Set
			If (Me._appdate.Equals(value) = false) Then
				Me.OnappdateChanging(value)
				Me.SendPropertyChanging
				Me._appdate = value
				Me.SendPropertyChanged("appdate")
				Me.OnappdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_app_staff_name", DbType:="NVarChar(MAX)")>  _
	Public Property app_staff_name() As String
		Get
			Return Me._app_staff_name
		End Get
		Set
			If (String.Equals(Me._app_staff_name, value) = false) Then
				Me.Onapp_staff_nameChanging(value)
				Me.SendPropertyChanging
				Me._app_staff_name = value
				Me.SendPropertyChanged("app_staff_name")
				Me.Onapp_staff_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WRITE_AT", DbType:="NVarChar(MAX)")>  _
	Public Property WRITE_AT() As String
		Get
			Return Me._WRITE_AT
		End Get
		Set
			If (String.Equals(Me._WRITE_AT, value) = false) Then
				Me.OnWRITE_ATChanging(value)
				Me.SendPropertyChanging
				Me._WRITE_AT = value
				Me.SendPropertyChanged("WRITE_AT")
				Me.OnWRITE_ATChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WRITE_DATE", DbType:="Date")>  _
	Public Property WRITE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._WRITE_DATE
		End Get
		Set
			If (Me._WRITE_DATE.Equals(value) = false) Then
				Me.OnWRITE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._WRITE_DATE = value
				Me.SendPropertyChanged("WRITE_DATE")
				Me.OnWRITE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_BY", DbType:="NVarChar(MAX)")>  _
	Public Property CREATE_BY() As String
		Get
			Return Me._CREATE_BY
		End Get
		Set
			If (String.Equals(Me._CREATE_BY, value) = false) Then
				Me.OnCREATE_BYChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_BY = value
				Me.SendPropertyChanged("CREATE_BY")
				Me.OnCREATE_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_DATE", DbType:="Date")>  _
	Public Property CREATE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CREATE_DATE
		End Get
		Set
			If (Me._CREATE_DATE.Equals(value) = false) Then
				Me.OnCREATE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_DATE = value
				Me.SendPropertyChanged("CREATE_DATE")
				Me.OnCREATE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATE_CONFIRM", DbType:="Date")>  _
	Public Property DATE_CONFIRM() As System.Nullable(Of Date)
		Get
			Return Me._DATE_CONFIRM
		End Get
		Set
			If (Me._DATE_CONFIRM.Equals(value) = false) Then
				Me.OnDATE_CONFIRMChanging(value)
				Me.SendPropertyChanging
				Me._DATE_CONFIRM = value
				Me.SendPropertyChanged("DATE_CONFIRM")
				Me.OnDATE_CONFIRMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_YEAR", DbType:="NChar(4)")>  _
	Public Property YEAR() As String
		Get
			Return Me._YEAR
		End Get
		Set
			If (String.Equals(Me._YEAR, value) = false) Then
				Me.OnYEARChanging(value)
				Me.SendPropertyChanging
				Me._YEAR = value
				Me.SendPropertyChanged("YEAR")
				Me.OnYEARChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Loacation_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Loacation_Name() As String
		Get
			Return Me._Loacation_Name
		End Get
		Set
			If (String.Equals(Me._Loacation_Name, value) = false) Then
				Me.OnLoacation_NameChanging(value)
				Me.SendPropertyChanging
				Me._Loacation_Name = value
				Me.SendPropertyChanged("Loacation_Name")
				Me.OnLoacation_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Loacation_ADDR", DbType:="NVarChar(MAX)")>  _
	Public Property Loacation_ADDR() As String
		Get
			Return Me._Loacation_ADDR
		End Get
		Set
			If (String.Equals(Me._Loacation_ADDR, value) = false) Then
				Me.OnLoacation_ADDRChanging(value)
				Me.SendPropertyChanging
				Me._Loacation_ADDR = value
				Me.SendPropertyChanged("Loacation_ADDR")
				Me.OnLoacation_ADDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tel", DbType:="NVarChar(MAX)")>  _
	Public Property tel() As String
		Get
			Return Me._tel
		End Get
		Set
			If (String.Equals(Me._tel, value) = false) Then
				Me.OntelChanging(value)
				Me.SendPropertyChanging
				Me._tel = value
				Me.SendPropertyChanged("tel")
				Me.OntelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fax", DbType:="NVarChar(MAX)")>  _
	Public Property Fax() As String
		Get
			Return Me._Fax
		End Get
		Set
			If (String.Equals(Me._Fax, value) = false) Then
				Me.OnFaxChanging(value)
				Me.SendPropertyChanging
				Me._Fax = value
				Me.SendPropertyChanged("Fax")
				Me.OnFaxChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVEFACT", DbType:="Int")>  _
	Public Property ACTIVEFACT() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVEFACT
		End Get
		Set
			If (Me._ACTIVEFACT.Equals(value) = false) Then
				Me.OnACTIVEFACTChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVEFACT = value
				Me.SendPropertyChanged("ACTIVEFACT")
				Me.OnACTIVEFACTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_FILE_UPLOAD", DbType:="Int")>  _
	Public Property STATUS_FILE_UPLOAD() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_FILE_UPLOAD
		End Get
		Set
			If (Me._STATUS_FILE_UPLOAD.Equals(value) = false) Then
				Me.OnSTATUS_FILE_UPLOADChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_FILE_UPLOAD = value
				Me.SendPropertyChanged("STATUS_FILE_UPLOAD")
				Me.OnSTATUS_FILE_UPLOADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVNO_NEW", DbType:="NVarChar(MAX)")>  _
	Public Property RCVNO_NEW() As String
		Get
			Return Me._RCVNO_NEW
		End Get
		Set
			If (String.Equals(Me._RCVNO_NEW, value) = false) Then
				Me.OnRCVNO_NEWChanging(value)
				Me.SendPropertyChanging
				Me._RCVNO_NEW = value
				Me.SendPropertyChanged("RCVNO_NEW")
				Me.OnRCVNO_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_csn_staff_name", DbType:="NVarChar(MAX)")>  _
	Public Property csn_staff_name() As String
		Get
			Return Me._csn_staff_name
		End Get
		Set
			If (String.Equals(Me._csn_staff_name, value) = false) Then
				Me.Oncsn_staff_nameChanging(value)
				Me.SendPropertyChanging
				Me._csn_staff_name = value
				Me.SendPropertyChanged("csn_staff_name")
				Me.Oncsn_staff_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_THANM", DbType:="NVarChar(MAX)")>  _
	Public Property THANM() As String
		Get
			Return Me._THANM
		End Get
		Set
			If (String.Equals(Me._THANM, value) = false) Then
				Me.OnTHANMChanging(value)
				Me.SendPropertyChanging
				Me._THANM = value
				Me.SendPropertyChanged("THANM")
				Me.OnTHANMChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.HERB_PRODUCT_NOTIFIED_DETAIL")>  _
Partial Public Class HERB_PRODUCT_NOTIFIED_DETAIL
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _Trade_Name As String
	
	Private _Scientific_Name As String
	
	Private _Latin_Name As String
	
	Private _Thai_Name As String
	
	Private _English_Name As String
	
	Private _Extract As String
	
	Private _Producer As String
	
	Private _Production_Version As String
	
	Private _Quantity As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnTrade_NameChanging(value As String)
    End Sub
    Partial Private Sub OnTrade_NameChanged()
    End Sub
    Partial Private Sub OnScientific_NameChanging(value As String)
    End Sub
    Partial Private Sub OnScientific_NameChanged()
    End Sub
    Partial Private Sub OnLatin_NameChanging(value As String)
    End Sub
    Partial Private Sub OnLatin_NameChanged()
    End Sub
    Partial Private Sub OnThai_NameChanging(value As String)
    End Sub
    Partial Private Sub OnThai_NameChanged()
    End Sub
    Partial Private Sub OnEnglish_NameChanging(value As String)
    End Sub
    Partial Private Sub OnEnglish_NameChanged()
    End Sub
    Partial Private Sub OnExtractChanging(value As String)
    End Sub
    Partial Private Sub OnExtractChanged()
    End Sub
    Partial Private Sub OnProducerChanging(value As String)
    End Sub
    Partial Private Sub OnProducerChanged()
    End Sub
    Partial Private Sub OnProduction_VersionChanging(value As String)
    End Sub
    Partial Private Sub OnProduction_VersionChanged()
    End Sub
    Partial Private Sub OnQuantityChanging(value As String)
    End Sub
    Partial Private Sub OnQuantityChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Trade_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Trade_Name() As String
		Get
			Return Me._Trade_Name
		End Get
		Set
			If (String.Equals(Me._Trade_Name, value) = false) Then
				Me.OnTrade_NameChanging(value)
				Me.SendPropertyChanging
				Me._Trade_Name = value
				Me.SendPropertyChanged("Trade_Name")
				Me.OnTrade_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Scientific_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Scientific_Name() As String
		Get
			Return Me._Scientific_Name
		End Get
		Set
			If (String.Equals(Me._Scientific_Name, value) = false) Then
				Me.OnScientific_NameChanging(value)
				Me.SendPropertyChanging
				Me._Scientific_Name = value
				Me.SendPropertyChanged("Scientific_Name")
				Me.OnScientific_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Latin_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Latin_Name() As String
		Get
			Return Me._Latin_Name
		End Get
		Set
			If (String.Equals(Me._Latin_Name, value) = false) Then
				Me.OnLatin_NameChanging(value)
				Me.SendPropertyChanging
				Me._Latin_Name = value
				Me.SendPropertyChanged("Latin_Name")
				Me.OnLatin_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Thai_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Thai_Name() As String
		Get
			Return Me._Thai_Name
		End Get
		Set
			If (String.Equals(Me._Thai_Name, value) = false) Then
				Me.OnThai_NameChanging(value)
				Me.SendPropertyChanging
				Me._Thai_Name = value
				Me.SendPropertyChanged("Thai_Name")
				Me.OnThai_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_English_Name", DbType:="NVarChar(MAX)")>  _
	Public Property English_Name() As String
		Get
			Return Me._English_Name
		End Get
		Set
			If (String.Equals(Me._English_Name, value) = false) Then
				Me.OnEnglish_NameChanging(value)
				Me.SendPropertyChanging
				Me._English_Name = value
				Me.SendPropertyChanged("English_Name")
				Me.OnEnglish_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Extract", DbType:="NVarChar(MAX)")>  _
	Public Property Extract() As String
		Get
			Return Me._Extract
		End Get
		Set
			If (String.Equals(Me._Extract, value) = false) Then
				Me.OnExtractChanging(value)
				Me.SendPropertyChanging
				Me._Extract = value
				Me.SendPropertyChanged("Extract")
				Me.OnExtractChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Producer", DbType:="NVarChar(MAX)")>  _
	Public Property Producer() As String
		Get
			Return Me._Producer
		End Get
		Set
			If (String.Equals(Me._Producer, value) = false) Then
				Me.OnProducerChanging(value)
				Me.SendPropertyChanging
				Me._Producer = value
				Me.SendPropertyChanged("Producer")
				Me.OnProducerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Production_Version", DbType:="NVarChar(MAX)")>  _
	Public Property Production_Version() As String
		Get
			Return Me._Production_Version
		End Get
		Set
			If (String.Equals(Me._Production_Version, value) = false) Then
				Me.OnProduction_VersionChanging(value)
				Me.SendPropertyChanging
				Me._Production_Version = value
				Me.SendPropertyChanged("Production_Version")
				Me.OnProduction_VersionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Quantity", DbType:="NVarChar(MAX)")>  _
	Public Property Quantity() As String
		Get
			Return Me._Quantity
		End Get
		Set
			If (String.Equals(Me._Quantity, value) = false) Then
				Me.OnQuantityChanging(value)
				Me.SendPropertyChanging
				Me._Quantity = value
				Me.SendPropertyChanged("Quantity")
				Me.OnQuantityChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
