<?xml version="1.0" encoding="utf-8"?><Database Name="LGT_DRUG_DEMO" Class="LINQ_REPORTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.168;Initial Catalog=LGT_DRUG_DEMO;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LGT_DRUGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HERB_PRODUCT_REPORT_DETAIL" Member="HERB_PRODUCT_REPORT_DETAILs">
    <Type Name="HERB_PRODUCT_REPORT_DETAIL">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Scientific_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Packing_Size_Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Total_Quantity" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sale_Unit" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Manufacturer_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Voucher_Number" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IS_USE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HERB_PRODUCT_REPORT" Member="HERB_PRODUCT_REPORTs">
    <Type Name="HERB_PRODUCT_REPORT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_LCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_LCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCNNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNNO_NEW" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcntpcd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="rcv_staff_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cnsddate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="frtappdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="appdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="app_staff_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WRITE_AT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WRITE_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_CONFIRM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="YEAR" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="Loacation_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Loacation_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_FILE_UPLOAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_NEW" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="csn_staff_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THANM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HERB_PRODUCT_NOTIFIED" Member="HERB_PRODUCT_NOTIFIEDs">
    <Type Name="HERB_PRODUCT_NOTIFIED">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_LCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_LCN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCNNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNNO_NEW" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcntpcd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="rcv_staff_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cnsddate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="frtappdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="appdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="app_staff_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WRITE_AT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WRITE_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_CONFIRM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="YEAR" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="Loacation_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Loacation_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_FILE_UPLOAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_NEW" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="csn_staff_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THANM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HERB_PRODUCT_NOTIFIED_DETAIL" Member="HERB_PRODUCT_NOTIFIED_DETAILs">
    <Type Name="HERB_PRODUCT_NOTIFIED_DETAIL">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Trade_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Scientific_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Latin_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Thai_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="English_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Extract" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Producer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Production_Version" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>